MODES = {
    "balanced": {
        "material":       1.0,
        "king_safety":    1.0,
        "mobility":       1.0,
        "pawn_structure": 1.0,
        "king_attack":    1.0,
        "king_activity":  1.0,
        "piece_activity": 1.0,
    },
    "kasparov": {
        "material":       0.4,
        "king_safety":    0.3,
        "mobility":       2.0,
        "pawn_structure": 0.2,
        "king_attack":    5.0,
        "king_activity":  0.5,
        "piece_activity": 3.0,
    },
    "karpov": {
        "material":       1.0,
        "king_safety":    5.0,
        "mobility":       1.0,
        "pawn_structure": 1.5,
        "king_attack":    0.1,
        "king_activity":  0.5,
        "piece_activity": 0.2,
    },
    "carlsen": {
        "material":       2.5,
        "king_safety":    1.0,
        "mobility":       3.5,
        "pawn_structure": 1.2,
        "king_attack":    0.8,
        "king_activity":  2.0,
        "piece_activity": 3.5,
    },
    "kramnik": {
        "material":       2.5,
        "king_safety":    1.5,
        "mobility":       2.5,
        "pawn_structure": 2.5,
        "king_attack":    0.8,
        "king_activity":  0.1,
        "piece_activity": 2.5,
    },
}
