import type { PersonaStyle } from './types';

export const PERSONAS: PersonaStyle[] = [
  {
    id: 'firefighter',
    name: 'Tactical / Aggressive',
    nickname: 'The Firefighter',
    inspiration: 'Tal / Kasparov',
    riskProfile: 'Very High',
    preferredPosition: 'Open, sharp, chaotic',
    quote: 'Set the board on fire before the opponent can breathe.',
    copy: 'Sharp attacks, sacrifices, and forcing lines.',
    engineBehavior: 'Prefers gambits, open games, and tactical complications',
    thinkingText: 'The Firefighter is searching sacrifices and king pressure…',
    accentColor: '#ef4444',
    glowColor: 'rgba(239,68,68,0.35)',
    bgColor: 'rgba(239,68,68,0.06)',
    biases: {
      attack: 95,
      riskControl: 35,
      positionalDepth: 60,
      endgame: 55,
      adaptability: 75,
    },
  },
  {
    id: 'optimizer',
    name: 'Positional / Strategic',
    nickname: 'The Optimizer',
    inspiration: 'Petrosian',
    riskProfile: 'Low',
    preferredPosition: 'Closed, structural, long-term',
    quote: 'Small advantages become inevitability.',
    copy: 'Small advantages, structure, and long-term pressure.',
    engineBehavior: 'Builds structure, avoids risk, wins methodically',
    thinkingText: 'The Optimizer is calculating long-term structure…',
    accentColor: '#3b82f6',
    glowColor: 'rgba(59,130,246,0.35)',
    bgColor: 'rgba(59,130,246,0.06)',
    biases: {
      attack: 45,
      riskControl: 90,
      positionalDepth: 95,
      endgame: 75,
      adaptability: 70,
    },
  },
  {
    id: 'wall',
    name: 'Defensive / Counter',
    nickname: 'The Wall',
    inspiration: 'Karpov',
    riskProfile: 'Very Low',
    preferredPosition: 'Solid, restricted, endgame',
    quote: 'Absorb, neutralize, punish.',
    copy: 'Absorb pressure, neutralize threats, punish mistakes.',
    engineBehavior: 'Defends everything, waits for errors, then counterstrikes',
    thinkingText: 'The Wall is checking defensive resources…',
    accentColor: '#10b981',
    glowColor: 'rgba(16,185,129,0.35)',
    bgColor: 'rgba(16,185,129,0.06)',
    biases: {
      attack: 50,
      riskControl: 95,
      positionalDepth: 85,
      endgame: 80,
      adaptability: 75,
    },
  },
  {
    id: 'grinder',
    name: 'Universal Player',
    nickname: 'The Grinder',
    inspiration: 'Carlsen',
    riskProfile: 'Medium',
    preferredPosition: 'Any — adapts to the board',
    quote: 'No position is too equal to win.',
    copy: 'Adapts, simplifies, and wins technical positions.',
    engineBehavior: 'Adapts to any position, excels in endgames',
    thinkingText: 'The Grinder is looking for a technical edge…',
    accentColor: '#f59e0b',
    glowColor: 'rgba(245,158,11,0.35)',
    bgColor: 'rgba(245,158,11,0.06)',
    biases: {
      attack: 75,
      riskControl: 80,
      positionalDepth: 85,
      endgame: 95,
      adaptability: 95,
    },
  },
];

export const COUNCIL_PERSONA: PersonaStyle = {
  id: 'council',
  name: 'Multi-agent Debate',
  nickname: 'The Council',
  inspiration: 'All five minds',
  riskProfile: 'Adaptive',
  preferredPosition: 'Committee decision',
  quote: 'Let the personalities debate. The best move wins.',
  copy: 'All four personalities vote — the majority picks the reply.',
  engineBehavior: 'All personalities debate; majority vote decides the move',
  thinkingText: 'The Council is debating candidate moves…',
  accentColor: '#8b5cf6',
  glowColor: 'rgba(139,92,246,0.35)',
  bgColor: 'rgba(139,92,246,0.06)',
  biases: {
    attack: 75,
    riskControl: 80,
    positionalDepth: 85,
    endgame: 85,
    adaptability: 90,
  },
};

export const ALL_PERSONAS: PersonaStyle[] = [...PERSONAS, COUNCIL_PERSONA];

export function getPersona(id: string): PersonaStyle {
  return ALL_PERSONAS.find((p) => p.id === id) ?? COUNCIL_PERSONA;
}
