MODES = {
    "balanced": {
        "material":       1.0,
        "king_safety":    1.0,
        "mobility":       1.0,
        "pawn_structure": 1.0,
        "king_attack":    1.0,
        "piece_activity": 1.0,
        "king_activity":  1.0,
    },
    "karpov": {
        "material":       1.30,
        "king_safety":    1.30,
        "mobility":       1.70,
        "pawn_structure": 1.70,
        "king_attack":    1.00,
        "piece_activity": 1.00,
        "king_activity":  1.10,
    },
    "kasparov": {
        "material":       1.00,
        "king_safety":    0.70,
        "mobility":       1.30,
        "pawn_structure": 0.70,
        "king_attack":    1.30,
        "piece_activity": 0.85,
        "king_activity":  1.00,
    },
    "petrosian": {
        "material":       1.30,
        "king_safety":    1.70,
        "mobility":       1.70,
        "pawn_structure": 1.70,
        "king_attack":    0.70,
        "piece_activity": 1.15,
        "king_activity":  1.00,
    },
    "carlsen": {
        "material":       1.30,
        "king_safety":    1.00,
        "mobility":       1.30,
        "pawn_structure": 1.30,
        "king_attack":    1.30,
        "piece_activity": 0.85,
        "king_activity":  1.20,
    },
}