import type { PersonaStyle } from "./types"

export const PERSONAS: PersonaStyle[] = [
  {
    id: "optimizer",
    name: "Positional Strategist",
    nickname: "Petrosian",
    profileName: "Petrosian Mode",
    subtitle: "Defensive Strategist",
    inspiration: "Petrosian",
    riskProfile: "Restrained",
    preferredPosition: "Quiet pressure and long files",
    quote: "Turn activity into weakness.",
    copy: "Quiet pressure. No counterplay.",
    description:
      "Locks the board, trims counterplay, and improves the worst piece first.",
    engineBehavior: "Clamps counterplay and keeps squeezing.",
    thinkingText: "Petrosian is closing the board...",
    accentColor: "#537ea8",
    glowColor: "rgba(83,126,168,0.28)",
    bgColor: "rgba(83,126,168,0.08)",
    avatar: "/avatars/optimizer.svg",
    biases: {
      attack: 44,
      riskControl: 92,
      positionalDepth: 96,
      endgame: 78,
      adaptability: 72,
    },
    weights: {
      material: 18,
      kingSafety: 27,
      kingAttack: 8,
      mobility: 11,
      pawnStructure: 22,
      pieceActivity: 14,
      kingActivity: 0,
    },
  },
  {
    id: "firefighter",
    name: "Tactical Attacker",
    nickname: "Tal",
    profileName: "Tal Mode",
    subtitle: "Chaos Attacker",
    inspiration: "Tal",
    riskProfile: "Wild",
    preferredPosition: "Open lines and exposed kings",
    quote: "Complicate first. Count later.",
    copy: "Open lines. Exposed kings.",
    description:
      "Pushes initiative, sacrifices when needed, and hunts the king.",
    engineBehavior: "Forcing lines first. Safety later.",
    thinkingText: "Tal is looking for fire...",
    accentColor: "#c75444",
    glowColor: "rgba(199,84,68,0.3)",
    bgColor: "rgba(199,84,68,0.08)",
    avatar: "/avatars/firefighter.svg",
    biases: {
      attack: 96,
      riskControl: 32,
      positionalDepth: 58,
      endgame: 50,
      adaptability: 76,
    },
    weights: {
      material: 10,
      kingSafety: 8,
      kingAttack: 28,
      mobility: 17,
      pawnStructure: 8,
      pieceActivity: 24,
      kingActivity: 5,
    },
  },
  {
    id: "wall",
    name: "Precision Fighter",
    nickname: "Fischer",
    profileName: "Fischer Mode",
    subtitle: "Precision Fighter",
    inspiration: "Fischer",
    riskProfile: "Measured",
    preferredPosition: "Direct central contests",
    quote: "Find the clean move. Press it.",
    copy: "Exact play. Direct punishment.",
    description:
      "Claims the center, punishes drift, and keeps calculation clean.",
    engineBehavior: "Exact development. No loose concessions.",
    thinkingText: "Fischer is checking the clean line...",
    accentColor: "#be8b3d",
    glowColor: "rgba(190,139,61,0.28)",
    bgColor: "rgba(190,139,61,0.08)",
    avatar: "/avatars/wall.svg",
    biases: {
      attack: 72,
      riskControl: 74,
      positionalDepth: 87,
      endgame: 70,
      adaptability: 80,
    },
    weights: {
      material: 20,
      kingSafety: 17,
      kingAttack: 16,
      mobility: 16,
      pawnStructure: 11,
      pieceActivity: 20,
      kingActivity: 0,
    },
  },
  {
    id: "grinder",
    name: "Universal Endgame Player",
    nickname: "Carlsen",
    profileName: "Carlsen Mode",
    subtitle: "Adaptive Grinder",
    inspiration: "Carlsen",
    riskProfile: "Adaptive",
    preferredPosition: "Any playable ending",
    quote: "Equal is still work.",
    copy: "Keep the board. Keep pressing.",
    description:
      "Improves everything, keeps the game alive, and wins the slow questions.",
    engineBehavior: "Keeps pressing until the position slips.",
    thinkingText: "Carlsen is pressing the small edge...",
    accentColor: "#c97f8b",
    glowColor: "rgba(201,127,139,0.28)",
    bgColor: "rgba(201,127,139,0.08)",
    avatar: "/avatars/grinder.svg",
    biases: {
      attack: 74,
      riskControl: 81,
      positionalDepth: 87,
      endgame: 95,
      adaptability: 97,
    },
    weights: {
      material: 18,
      kingSafety: 15,
      kingAttack: 12,
      mobility: 17,
      pawnStructure: 12,
      pieceActivity: 18,
      kingActivity: 8,
    },
  },
]

export const COUNCIL_PERSONA: PersonaStyle = {
  id: "council",
  name: "Multi-Agent Debate",
  nickname: "Council",
  profileName: "Council Mode",
  subtitle: "Five-Mind Verdict",
  inspiration: "Grandmaster room",
  riskProfile: "Adaptive",
  preferredPosition: "The position the debate earns",
  quote: "Let the move survive the room.",
  copy: "Five voices. One move.",
  description: "A room of styles, reduced to one reply.",
  engineBehavior: "Debates candidate lines, then sends the survivor.",
  thinkingText: "The room is arguing the next move...",
  accentColor: "#201814",
  glowColor: "rgba(32,24,20,0.2)",
  bgColor: "rgba(32,24,20,0.08)",
  avatar: "/avatars/council.svg",
  biases: {
    attack: 75,
    riskControl: 80,
    positionalDepth: 86,
    endgame: 86,
    adaptability: 92,
  },
  weights: {
    material: 15,
    kingSafety: 17,
    kingAttack: 15,
    mobility: 15,
    pawnStructure: 14,
    pieceActivity: 14,
    kingActivity: 10,
  },
}

export const ALL_PERSONAS: PersonaStyle[] = [...PERSONAS, COUNCIL_PERSONA]

export function getPersona(id: string): PersonaStyle {
  return ALL_PERSONAS.find((persona) => persona.id === id) ?? COUNCIL_PERSONA
}
